# Generated by Django 5.2.14 on 2026-05-15 23:37

import apps.learning.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.TextField(max_length=600)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('worksheet', 'Worksheet'), ('audio', 'Audio'), ('video', 'Video'), ('slides', 'Slides'), ('link', 'External link')], default='pdf', max_length=20)),
                ('file', models.FileField(blank=True, upload_to=apps.learning.models.learning_material_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'mp3', 'm4a', 'wav', 'mp4', 'mov')), apps.learning.models.validate_learning_material_file])),
                ('external_url', models.URLField(blank=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=5)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='learning.category')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='learning_le_is_publ_046840_idx')],
            },
        ),
    ]
