# Generated by Django 5.2.14 on 2026-05-16 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to_email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_provider', models.CharField(default='resend', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sent_at',),
                'indexes': [models.Index(fields=['user', '-sent_at'], name='accounts_em_user_id_4f4d31_idx'), models.Index(fields=['code_hash', 'expires_at'], name='accounts_em_code_ha_8d5eb8_idx')],
            },
        ),
    ]
