# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailverificationchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationchallenge",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
