# Generated by Django 5.2.14 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="practitionerprofile",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="practitionerprofile",
            name="video_call_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="supportthread",
            name="contact_method",
            field=models.CharField(choices=[("text", "Text"), ("phone", "Phone call"), ("video", "Video call")], default="text", max_length=16),
        ),
    ]