# Generated by Django 5.2.11 on 2026-06-06 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def preserve_existing_support_state(apps, schema_editor):
    PractitionerProfile = apps.get_model("support", "PractitionerProfile")
    SupportThread = apps.get_model("support", "SupportThread")
    PractitionerProfile.objects.filter(is_available=True).update(availability_status="online")
    SupportThread.objects.filter(is_closed=True).update(status="closed", ended_at=models.F("updated_at"))
    SupportThread.objects.filter(is_closed=False).update(status="accepted", accepted_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_practitioner_connection_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=16)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ended', 'Ended'), ('missed', 'Missed')], default='ringing', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='SupportNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('support_request', 'Support request'), ('request_accepted', 'Request accepted'), ('request_rejected', 'Request rejected'), ('new_message', 'New message'), ('call_update', 'Call update')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=280)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupportSession',
            fields=[
            ],
            options={
                'verbose_name': 'support session',
                'verbose_name_plural': 'support sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('support.supportthread',),
        ),
        migrations.AlterModelOptions(
            name='practitionerprofile',
            options={'ordering': ('availability_status', 'next_available_at', 'display_name')},
        ),
        migrations.AddField(
            model_name='practitionerprofile',
            name='availability_status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy')], default='offline', max_length=16),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='accepted', max_length=16),
        ),
        migrations.RunPython(preserve_existing_support_state, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['practitioner', 'status', '-updated_at'], name='support_sup_practit_ff4662_idx'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='support.supportthread'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_support_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportnotification',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='support.supportthread'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['session', 'status', '-started_at'], name='support_cal_session_57c7a0_idx'),
        ),
        migrations.AddIndex(
            model_name='supportnotification',
            index=models.Index(fields=['recipient', 'read_at', '-created_at'], name='support_sup_recipie_0c0a40_idx'),
        ),
    ]
