# Generated by Django 5.2.11 on 2026-06-06 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_callsession_supportnotification_supportsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['thread', 'read_at', 'created_at'], name='support_sup_thread__a48181_idx'),
        ),
    ]
